"""slots error.

Revision ID: 59d61384e268
Revises: 60db81819c57
Create Date: 2026-07-12 19:21:57.823780

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '59d61384e268'
down_revision: Union[str, Sequence[str], None] = '60db81819c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
