"""nullable rem.

Revision ID: 60db81819c57
Revises: f51226158a61
Create Date: 2026-07-09 11:00:25.033408

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '60db81819c57'
down_revision: Union[str, Sequence[str], None] = 'f51226158a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
