"""increase password hash length.

Revision ID: f51226158a61
Revises: d4a7b9c1e2f0
Create Date: 2026-07-09 10:52:31.377642

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f51226158a61'
down_revision: Union[str, Sequence[str], None] = 'd4a7b9c1e2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cafe_name_address', 'cafes', ['name', 'address'])
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=320),
        existing_nullable=True,
    )
    op.alter_column(
        'users',
        'password_hash',
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'password_hash',
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.String(length=320),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.drop_constraint('uq_cafe_name_address', 'cafes', type_='unique')
    # ### end Alembic commands ###
